name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 8 * * MON"
  workflow_dispatch:

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: "liberica"
          java-version: "19"
      - uses: gradle-update/update-gradle-wrapper-action@v1
