name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 8 * * MON"
  workflow_dispatch:

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.3
      - uses: gradle/actions/setup-gradle@v3.3.1
        with:
          cache-read-only: true
      - uses: gradle-update/update-gradle-wrapper-action@v1.0.20
